server:
  port: 10086
spring:
  application:
    name: mq-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtualHost: /ems
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
#      exchange: topic.exchange
#    # 手动提交消息
#    listener:
#      simple:
#        acknowledge-mode: manual
#      direct:
#        acknowledge-mode: manual
